### ISSUE TITLE
 ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by zlin9** [ZhengJianwei2/CTFI-Net#1]
在运行main_cd.py与eval_cd.py出现如下错误，不知道如何修改，求助。
 self.G_pred1, self.G_pred2, self.G_pred3 = self.net_G(img_in1, img_in2)
ValueError: too many values to unpack (expected 3)

**Comment by ZhengJianwei2** [comment]
代码已修正
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Mar 9, 2023 07:17 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[ZhengJianwei2/DMINet]  ValueError: too many values to unpack (expected 3) (Issue #1)

&nbsp;



 
在运行main_cd.py与eval_cd.py出现如下错误，不知道如何修改，求助。
 self.G_pred1, self.G_pred2, self.G_pred3 = self.net_G(img_in1, img_in2)
 ValueError: too many values to unpack (expected 3)

**Comment by weizc777** [comment]
我也遇到了这个问题，请问一下是如何修改的呢？

**Comment by zlin9** [comment]
> 

抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？

**Comment by ZhengJianwei2** [comment]
> > 
> 
> 抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？

之前登错了账号，发现没修改成功，现已修改，感谢持续关注！

**Comment by zlin9** [comment]
> > > 
> > 
> > 
> > 抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？
> 
> 之前登错了账号，发现没修改成功，现已修改，感谢持续关注！

十分感谢您的回复和帮助，问题已经解决！

**Comment by ZhengJianwei2** [comment]
> > > > 
> > > 
> > > 
> > > 抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？
> > 
> > 
> > 之前登错了账号，发现没修改成功，现已修改，感谢持续关注！
> 
> 十分感谢您的回复和帮助，问题已经解决！

之前Github上DMINet的代码train.py中优化器放的是Adam，但在实际训练中我们使用的SGD，现已修正，十分抱歉，如果有跑代码，劳烦注意一下，性能可能有点差别。

**Comment by zlin9** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？
> > > 
> > > 
> > > 之前登错了账号，发现没修改成功，现已修改，感谢持续关注！
> > 
> > 
> > 十分感谢您的回复和帮助，问题已经解决！
> 
> 之前Github上DMINet的代码train.py中优化器放的是Adam，但在实际训练中我们使用的SGD，现已修正，十分抱歉，如果有跑代码，劳烦注意一下，性能可能有点差别。

感谢您的提醒！

**Comment by zlin9** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 抱歉，我也不知道，作者说已经修改了，但是我运行仍存在错误，请问你现在解决了吗？
> > > 
> > > 
> > > 之前登错了账号，发现没修改成功，现已修改，感谢持续关注！
> > 
> > 
> > 十分感谢您的回复和帮助，问题已经解决！
> 
> 之前Github上DMINet的代码train.py中优化器放的是Adam，但在实际训练中我们使用的SGD，现已修正，十分抱歉，如果有跑代码，劳烦注意一下，性能可能有点差别。

您好，我还有个问题想向您确认一下，您论文中的指标（以F1为例），是指的模型训练结果中的F1_1，而不是mf1，是吗？

**Comment by fengyuchao97** [comment]
> 

是的，F1_1是专指变化区域的F1-Score

**Comment by Tempest-jpg** [comment]
self.G_loss =  self._pxl_loss(self.G_pred1, gt) + self._pxl_loss(self.G_pred2, gt) + 0.5*(self._pxl_loss(self.self.G_middle1, gt)+self._pxl_loss(self.self.G_middle2, gt))
AttributeError: 'CDTrainer' object has no attribute 'self'
训练时总会出现这个错误，但是一旦删掉一个额外的self，使用demo.py生成特征图是则又会报错，请问该如何解决

**Comment by fengyuchao97** [comment]
正解如下，里面多打了两个self
self.G_loss = self._pxl_loss(self.G_pred1, gt) + self._pxl_loss(self.G_pred2, gt) + 0.5*(self._pxl_loss(self.G_middle1, gt)+self._pxl_loss(self.G_middle2, gt))
&nbsp;


1149160349
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 晚上9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengJianwei2/DMINet]  ValueError: too many values to unpack (expected 3) (Issue #1)





 
self.G_loss =  self._pxl_loss(self.G_pred1, gt) + self._pxl_loss(self.G_pred2, gt) + 0.5*(self._pxl_loss(self.self.G_middle1, gt)+self._pxl_loss(self.self.G_middle2, gt))
 AttributeError: 'CDTrainer' object has no attribute 'self'
 训练时总会出现这个错误，但是一旦删掉一个额外的self，使用demo.py生成特征图是则又会报错，请问该如何解决

**Comment by dpt000121** [comment]
求问：在运行main_cd.py时，遇到如下错误，请问如何修改呢
hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608

**Comment by Tempest-jpg** [comment]
请问，在运行demo.py时遇到这个问题该如何解决：
Traceback (most recent call last):
  File "/home/B/hyf/DMI/demo.py", line 70, in <module>
    score_map = model._forward_pass(batch)
  File "/home/B/hyf/DMI/models/basic_model.py", line 64, in _forward_pass
    return self._visualize_pred()
  File "/home/B/hyf/DMI/models/basic_model.py", line 52, in _visualize_pred
    pred = torch.argmax(self.G_pred, dim=1, keepdim=True)
TypeError: argmax(): argument 'input' (position 1) must be Tensor, not tuple

**Comment by fengyuchao97** [comment]
'--net_G' 选择 DMINet, github代码已修改
&nbsp;


1149160349
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengJianwei2/DMINet]  ValueError: too many values to unpack (expected 3) (Issue #1)





 
请问，在运行demo.py时遇到这个问题该如何解决：
 Traceback (most recent call last):
 File "/home/B/hyf/DMI/demo.py", line 70, in 
 score_map = model._forward_pass(batch)
 File "/home/B/hyf/DMI/models/basic_model.py", line 64, in _forward_pass
 return self._visualize_pred()
 File "/home/B/hyf/DMI/models/basic_model.py", line 52, in _visualize_pred
 pred = torch.argmax(self.G_pred, dim=1, keepdim=True)
 TypeError: argmax(): argument 'input' (position 1) must be Tensor, not tuple

**Comment by fengyuchao97** [comment]
你好，这个错误我没遇到过，报错位置在哪个文件夹呀
&nbsp;


1149160349
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 下午2:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengJianwei2/DMINet]  ValueError: too many values to unpack (expected 3) (Issue #1)





 
求问：在运行main_cd.py时，遇到如下错误，请问如何修改呢
 hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask],
 IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608

**Comment by dpt000121** [comment]
> 你好，这个错误我没遇到过，报错位置在哪个文件夹呀 &nbsp; 1149160349 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月7日(星期五) 下午2:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ZhengJianwei2/DMINet] ValueError: too many values to unpack (expected 3) (Issue #1) 求问：在运行main_cd.py时，遇到如下错误，请问如何修改呢 hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask], IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，这是完整的报错信息：  在metric_tool的报错位置打印看了一下，形参label_gt.size和label_pred.size的shape都为(65536,)

Begin evaluation...
/root/anaconda3/envs/dminet/lib/python3.6/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/root/anaconda3/envs/dminet/lib/python3.6/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "main_cd.py", line 74, in <module>
    train(args)
  File "main_cd.py", line 16, in train
    model.train_models()
  File "/slr/docker_share/dminet/DMINet-main/models/trainer.py", line 303, in train_models
    self._collect_running_batch_states()
  File "/slr/docker_share/dminet/DMINet-main/models/trainer.py", line 174, in _collect_running_batch_states
    running_acc = self._update_metric()
  File "/slr/docker_share/dminet/DMINet-main/models/trainer.py", line 169, in _update_metric
    current_score = self.running_metric.update_cm(pr=G_pred.cpu().numpy(), gt=target.cpu().numpy())
  File "/slr/docker_share/dminet/DMINet-main/misc/metric_tool.py", line 56, in update_cm
    val = get_confuse_matrix(num_classes=self.n_class, label_gts=gt, label_preds=pr)
  File "/slr/docker_share/dminet/DMINet-main/misc/metric_tool.py", line 169, in get_confuse_matrix
    confusion_matrix += __fast_hist(lt.flatten(), lp.flatten())
  File "/slr/docker_share/dminet/DMINet-main/misc/metric_tool.py", line 161, in __fast_hist
    hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608

**Comment by dpt000121** [comment]
> 你好，这个错误我没遇到过，报错位置在哪个文件夹呀 &nbsp; 1149160349 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月7日(星期五) 下午2:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ZhengJianwei2/DMINet] ValueError: too many values to unpack (expected 3) (Issue #1) 求问：在运行main_cd.py时，遇到如下错误，请问如何修改呢 hist = np.bincount(num_classes * label_gt[mask].astype(int) + label_pred[mask], IndexError: boolean index did not match indexed array along dimension 0; dimension is 65536 but corresponding boolean dimension is 196608 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
您好，拜托您我可以看一下您dataconfig.py文件和数据集目录吗，还有数据集目录下的train.txt和val.txt文件我可以看一下您的，确认一下我的是否正确吗

**Comment by JackLiu-97** [comment]
您好，能提供一下论文中热力图的可视化代码吗，自己从网上找的一直没有调好。
