### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by JackLiu-97** [ZhengJianwei2/CTFI-Net#3]
你好，我在跑demo.py时报错
initialize network with normal
Traceback (most recent call last):
  File "D:\DMINet-main\demo.py", line 64, in <module>
    model.load_checkpoint(args.checkpoint_name)
  File "D:\DMINet-main\models\basic_model.py", line 35, in load_checkpoint
    self.net_G.load_state_dict(checkpoint['model_G_state_dict'])
  File "C:\Users\chenlong\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DMINet:
	Missing key(s) in state_dict: "resnet.conv1.weight", "resnet.bn1.weight", "resnet.bn1.bias", "resnet.bn1.running_mean", "resnet.bn1.running_var", "resnet.layer1.0.conv1.weight", "resnet.layer1.0.bn1.weight", "resnet.layer1.0.bn1.bias", "resnet.layer1.0.bn1.running_mean", "resnet.layer1.0.bn1.running_var", "resnet.layer1.0.conv2.weight", "resnet.layer1.0.bn2.weight", "resnet.layer1.0.bn2.bias", "resnet.layer1.0.bn2.running_mean", "resnet.layer1.0.bn2.running_var", "resnet.layer1.1.conv1.weight", "resnet.layer1.1.bn1.weight", "resnet.layer1.1.bn1.bias", "resnet.layer1.1.bn1.running_mean", "resnet.layer1.1.bn1.running_var", "resnet.layer1.1.conv2.weight", "resnet.layer1.1.bn2.weight", "resnet.layer1.1.bn2.bias", "resnet.layer1.1.bn2.running_mean", "resnet.layer1.1.bn2.running_var", "resnet.layer2.0.conv1.weight", "resnet.layer2.0.bn1.weight", "resnet.layer2.0.bn1.bias", "resnet.layer2.0.bn1.running_mean", "resnet.layer2.0.bn1.running_var", "resnet.layer2.0.conv2.weight", "resnet.layer2.0.bn2.weight", "resnet.layer2.0.bn2.bias", "resnet.layer2.0.bn2.running_mean", "resnet.layer2.0.bn2.running_var", "resnet.layer2.0.downsample.0.weight", "resnet.layer2.0.downsample.1.weight", "resnet.layer2.0.downsample.1.bias", "resnet.layer2.0.downsample.1.running_mean", "resnet.layer2.0.downsample.1.running_var", "resnet.layer2.1.conv1.weight", "resnet.layer2.1.bn1.weight", "resnet.layer2.1.bn1.bias", "resnet.layer2.1.bn1.running_mean", "resnet.layer2.1.bn1.running_var", "resnet.layer2.1.conv2.weight", "resnet.layer2.1.bn2.weight", "resnet.layer2.1.bn2.bias", "resnet.layer2.1.bn2.running_mean", "resnet.layer2.1.bn2.running_var", "resnet.layer3.0.conv1.weight", "resnet.layer3.0.bn1.weight", "resnet.layer3.0.bn1.bias", "resnet.layer3.0.bn1.running_mean", "resnet.layer3.0.bn1.running_var", "resnet.layer3.0.conv2.weight", "resnet.layer3.0.bn2.weight", "resnet.layer3.0.bn2.bias", "resnet.layer3.0.bn2.running_mean", "resnet.layer3.0.bn2.running_var", "resnet.layer3.0.downsample.0.weight", "resnet.layer3.0.downsample.1.weight", "resnet.layer3.0.downsample.1.bias", "resnet.layer3.0.downsample.1.running_mean", "resnet.layer3.0.downsample.1.running_var", "resnet.layer3.1.conv1.weight", "resnet.layer3.1.bn1.weight", "resnet.layer3.1.bn1.bias", "resnet.layer3.1.bn1.running_mean", "resnet.layer3.1.bn1.running_var", "resnet.layer3.1.conv2.weight", "resnet.layer3.1.bn2.weight", "resnet.layer3.1.bn2.bias", "resnet.layer3.1.bn2.running_mean", "resnet.layer3.1.bn2.running_var", "resnet.fc.weight", "resnet.fc.bias", "cross2.gamma", "cross2.query1.weight", "cross2.query1.bias", "cross2.key1.weight", "cross2.key1.bias", "cross2.value1.weight", "cross2.value1.bias", "cross2.query2.weight", "cross2.query2.bias", "cross2.key2.weight", "cross2.key2.bias", "cross2.value2.weight", "cross2.value2.bias", "cross2.conv_cat.0.weight", "cross2.conv_cat.1.weight", "cross2.conv_cat.1.bias", "cross2.conv_cat.1.running_mean", "cross2.conv_cat.1.running_var", "cross3.gamma", "cross3.query1.weight", "cross3.query1.bias", "cross3.key1.weight", "cross3.key1.bias", "cross3.value1.weight", "cross3.value1.bias", "cross3.query2.weight", "cross3.query2.bias", "cross3.key2.weight", "cross3.key2.bias", "cross3.value2.weight", "cross3.value2.bias", "cross3.conv_cat.0.weight", "cross3.conv_cat.1.weight", "cross3.conv_cat.1.bias", "cross3.conv_cat.1.running_mean", "cross3.conv_cat.1.running_var", "cross4.gamma", "cross4.query1.weight", "cross4.query1.bias", "cross4.key1.weight", "cross4.key1.bias", "cross4.value1.weight", "cross4.value1.bias", "cross4.query2.weight", "cross4.query2.bias", "cross4.key2.weight", "cross4.key2.bias", "cross4.value2.weight", "cross4.value2.bias", "cross4.conv_cat.0.weight", "cross4.conv_cat.1.weight", "cross4.conv_cat.1.bias", "cross4.conv_cat.1.running_mean", "cross4.conv_cat.1.running_var", "Translayer2_1.conv.weight", "Translayer2_1.bn.weight", "Translayer2_1.bn.bias", "Translayer2_1.bn.running_mean", "Translayer2_1.bn.running_var", "fam32_1.conv_d1.weight", "fam32_1.conv_d1.bias", "fam32_1.conv_l.weight", "fam32_1.conv_l.bias", "fam32_1.conv3.weight", "fam32_1.conv3.bias", "fam32_1.bn3.weight", "fam32_1.bn3.bias", "fam32_1.bn3.running_mean", "fam32_1.bn3.running_var", "Translayer3_1.conv.weight", "Translayer3_1.bn.weight", "Translayer3_1.bn.bias", "Translayer3_1.bn.running_mean", "Translayer3_1.bn.running_var", "fam43_1.conv_d1.weight", "fam43_1.conv_d1.bias", "fam43_1.conv_l.weight", "fam43_1.conv_l.bias", "fam43_1.conv3.weight", "fam43_1.conv3.bias", "fam43_1.bn3.weight", "fam43_1.bn3.bias", "fam43_1.bn3.running_mean", "fam43_1.bn3.running_var", "Translayer2_2.conv.weight", "Translayer2_2.bn.weight", "Translayer2_2.bn.bias", "Translayer2_2.bn.running_mean", "Translayer2_2.bn.running_var", "fam32_2.conv_d1.weight", "fam32_2.conv_d1.bias", "fam32_2.conv_l.weight", "fam32_2.conv_l.bias", "fam32_2.conv3.weight", "fam32_2.conv3.bias", "fam32_2.bn3.weight", "fam32_2.bn3.bias", "fam32_2.bn3.running_mean", "fam32_2.bn3.running_var", "Translayer3_2.conv.weight", "Translayer3_2.bn.weight", "Translayer3_2.bn.bias", "Translayer3_2.bn.running_mean", "Translayer3_2.bn.running_var", "fam43_2.conv_d1.weight", "fam43_2.conv_d1.bias", "fam43_2.conv_l.weight", "fam43_2.conv_l.bias", "fam43_2.conv3.weight", "fam43_2.conv3.bias", "fam43_2.bn3.weight", "fam43_2.bn3.bias", "fam43_2.bn3.running_mean", "fam43_2.bn3.running_var", "final.0.conv.weight", "final.0.conv.bias", "final.0.bn.weight", "final.0.bn.bias", "final.0.bn.running_mean", "final.0.bn.running_var", "final.1.conv.weight", "final.1.conv.bias", "final2.0.conv.weight", "final2.0.conv.bias", "final2.0.bn.weight", "final2.0.bn.bias", "final2.0.bn.running_mean", "final2.0.bn.running_var", "final2.1.conv.weight", "final2.1.conv.bias", "final_2.0.conv.weight", "final_2.0.conv.bias", "final_2.0.bn.weight", "final_2.0.bn.bias", "final_2.0.bn.running_mean", "final_2.0.bn.running_var", "final_2.1.conv.weight", "final_2.1.conv.bias", "final2_2.0.conv.weight", "final2_2.0.conv.bias", "final2_2.0.bn.weight", "final2_2.0.bn.bias", "final2_2.0.bn.running_mean", "final2_2.0.bn.running_var", "final2_2.1.conv.weight", "final2_2.1.conv.bias". 
	Unexpected key(s) in state_dict: "module.resnet.conv1.weight", "module.resnet.bn1.weight", "module.resnet.bn1.bias", "module.resnet.bn1.running_mean", "module.resnet.bn1.running_var", "module.resnet.bn1.num_batches_tracked", "module.resnet.layer1.0.conv1.weight", "module.resnet.layer1.0.bn1.weight", "module.resnet.layer1.0.bn1.bias", "module.resnet.layer1.0.bn1.running_mean", "module.resnet.layer1.0.bn1.running_var", "module.resnet.layer1.0.bn1.num_batches_tracked", "module.resnet.layer1.0.conv2.weight", "module.resnet.layer1.0.bn2.weight", "module.resnet.layer1.0.bn2.bias", "module.resnet.layer1.0.bn2.running_mean", "module.resnet.layer1.0.bn2.running_var", "module.resnet.layer1.0.bn2.num_batches_tracked", "module.resnet.layer1.1.conv1.weight", "module.resnet.layer1.1.bn1.weight", "module.resnet.layer1.1.bn1.bias", "module.resnet.layer1.1.bn1.running_mean", "module.resnet.layer1.1.bn1.running_var", "module.resnet.layer1.1.bn1.num_batches_tracked", "module.resnet.layer1.1.conv2.weight", "module.resnet.layer1.1.bn2.weight", "module.resnet.layer1.1.bn2.bias", "module.resnet.layer1.1.bn2.running_mean", "module.resnet.layer1.1.bn2.running_var", "module.resnet.layer1.1.bn2.num_batches_tracked", "module.resnet.layer2.0.conv1.weight", "module.resnet.layer2.0.bn1.weight", "module.resnet.layer2.0.bn1.bias", "module.resnet.layer2.0.bn1.running_mean", "module.resnet.layer2.0.bn1.running_var", "module.resnet.layer2.0.bn1.num_batches_tracked", "module.resnet.layer2.0.conv2.weight", "module.resnet.layer2.0.bn2.weight", "module.resnet.layer2.0.bn2.bias", "module.resnet.layer2.0.bn2.running_mean", "module.resnet.layer2.0.bn2.running_var", "module.resnet.layer2.0.bn2.num_batches_tracked", "module.resnet.layer2.0.downsample.0.weight", "module.resnet.layer2.0.downsample.1.weight", "module.resnet.layer2.0.downsample.1.bias", "module.resnet.layer2.0.downsample.1.running_mean", "module.resnet.layer2.0.downsample.1.running_var", "module.resnet.layer2.0.downsample.1.num_batches_tracked", "module.resnet.layer2.1.conv1.weight", "module.resnet.layer2.1.bn1.weight", "module.resnet.layer2.1.bn1.bias", "module.resnet.layer2.1.bn1.running_mean", "module.resnet.layer2.1.bn1.running_var", "module.resnet.layer2.1.bn1.num_batches_tracked", "module.resnet.layer2.1.conv2.weight", "module.resnet.layer2.1.bn2.weight", "module.resnet.layer2.1.bn2.bias", "module.resnet.layer2.1.bn2.running_mean", "module.resnet.layer2.1.bn2.running_var", "module.resnet.layer2.1.bn2.num_batches_tracked", "module.resnet.layer3.0.conv1.weight", "module.resnet.layer3.0.bn1.weight", "module.resnet.layer3.0.bn1.bias", "module.resnet.layer3.0.bn1.running_mean", "module.resnet.layer3.0.bn1.running_var", "module.resnet.layer3.0.bn1.num_batches_tracked", "module.resnet.layer3.0.conv2.weight", "module.resnet.layer3.0.bn2.weight", "module.resnet.layer3.0.bn2.bias", "module.resnet.layer3.0.bn2.running_mean", "module.resnet.layer3.0.bn2.running_var", "module.resnet.layer3.0.bn2.num_batches_tracked", "module.resnet.layer3.0.downsample.0.weight", "module.resnet.layer3.0.downsample.1.weight", "module.resnet.layer3.0.downsample.1.bias", "module.resnet.layer3.0.downsample.1.running_mean", "module.resnet.layer3.0.downsample.1.running_var", "module.resnet.layer3.0.downsample.1.num_batches_tracked", "module.resnet.layer3.1.conv1.weight", "module.resnet.layer3.1.bn1.weight", "module.resnet.layer3.1.bn1.bias", "module.resnet.layer3.1.bn1.running_mean", "module.resnet.layer3.1.bn1.running_var", "module.resnet.layer3.1.bn1.num_batches_tracked", "module.resnet.layer3.1.conv2.weight", "module.resnet.layer3.1.bn2.weight", "module.resnet.layer3.1.bn2.bias", "module.resnet.layer3.1.bn2.running_mean", "module.resnet.layer3.1.bn2.running_var", "module.resnet.layer3.1.bn2.num_batches_tracked", "module.resnet.fc.weight", "module.resnet.fc.bias", "module.cross2.gamma", "module.cross2.query1.weight", "module.cross2.query1.bias", "module.cross2.key1.weight", "module.cross2.key1.bias", "module.cross2.value1.weight", "module.cross2.value1.bias", "module.cross2.query2.weight", "module.cross2.query2.bias", "module.cross2.key2.weight", "module.cross2.key2.bias", "module.cross2.value2.weight", "module.cross2.value2.bias", "module.cross2.conv_cat.0.weight", "module.cross2.conv_cat.1.weight", "module.cross2.conv_cat.1.bias", "module.cross2.conv_cat.1.running_mean", "module.cross2.conv_cat.1.running_var", "module.cross2.conv_cat.1.num_batches_tracked", "module.cross3.gamma", "module.cross3.query1.weight", "module.cross3.query1.bias", "module.cross3.key1.weight", "module.cross3.key1.bias", "module.cross3.value1.weight", "module.cross3.value1.bias", "module.cross3.query2.weight", "module.cross3.query2.bias", "module.cross3.key2.weight", "module.cross3.key2.bias", "module.cross3.value2.weight", "module.cross3.value2.bias", "module.cross3.conv_cat.0.weight", "module.cross3.conv_cat.1.weight", "module.cross3.conv_cat.1.bias", "module.cross3.conv_cat.1.running_mean", "module.cross3.conv_cat.1.running_var", "module.cross3.conv_cat.1.num_batches_tracked", "module.cross4.gamma", "module.cross4.query1.weight", "module.cross4.query1.bias", "module.cross4.key1.weight", "module.cross4.key1.bias", "module.cross4.value1.weight", "module.cross4.value1.bias", "module.cross4.query2.weight", "module.cross4.query2.bias", "module.cross4.key2.weight", "module.cross4.key2.bias", "module.cross4.value2.weight", "module.cross4.value2.bias", "module.cross4.conv_cat.0.weight", "module.cross4.conv_cat.1.weight", "module.cross4.conv_cat.1.bias", "module.cross4.conv_cat.1.running_mean", "module.cross4.conv_cat.1.running_var", "module.cross4.conv_cat.1.num_batches_tracked", "module.Translayer2_1.conv.weight", "module.Translayer2_1.bn.weight", "module.Translayer2_1.bn.bias", "module.Translayer2_1.bn.running_mean", "module.Translayer2_1.bn.running_var", "module.Translayer2_1.bn.num_batches_tracked", "module.fam32_1.conv_d1.weight", "module.fam32_1.conv_d1.bias", "module.fam32_1.conv_l.weight", "module.fam32_1.conv_l.bias", "module.fam32_1.conv3.weight", "module.fam32_1.conv3.bias", "module.fam32_1.bn3.weight", "module.fam32_1.bn3.bias", "module.fam32_1.bn3.running_mean", "module.fam32_1.bn3.running_var", "module.fam32_1.bn3.num_batches_tracked", "module.Translayer3_1.conv.weight", "module.Translayer3_1.bn.weight", "module.Translayer3_1.bn.bias", "module.Translayer3_1.bn.running_mean", "module.Translayer3_1.bn.running_var", "module.Translayer3_1.bn.num_batches_tracked", "module.fam43_1.conv_d1.weight", "module.fam43_1.conv_d1.bias", "module.fam43_1.conv_l.weight", "module.fam43_1.conv_l.bias", "module.fam43_1.conv3.weight", "module.fam43_1.conv3.bias", "module.fam43_1.bn3.weight", "module.fam43_1.bn3.bias", "module.fam43_1.bn3.running_mean", "module.fam43_1.bn3.running_var", "module.fam43_1.bn3.num_batches_tracked", "module.Translayer2_2.conv.weight", "module.Translayer2_2.bn.weight", "module.Translayer2_2.bn.bias", "module.Translayer2_2.bn.running_mean", "module.Translayer2_2.bn.running_var", "module.Translayer2_2.bn.num_batches_tracked", "module.fam32_2.conv_d1.weight", "module.fam32_2.conv_d1.bias", "module.fam32_2.conv_l.weight", "module.fam32_2.conv_l.bias", "module.fam32_2.conv3.weight", "module.fam32_2.conv3.bias", "module.fam32_2.bn3.weight", "module.fam32_2.bn3.bias", "module.fam32_2.bn3.running_mean", "module.fam32_2.bn3.running_var", "module.fam32_2.bn3.num_batches_tracked", "module.Translayer3_2.conv.weight", "module.Translayer3_2.bn.weight", "module.Translayer3_2.bn.bias", "module.Translayer3_2.bn.running_mean", "module.Translayer3_2.bn.running_var", "module.Translayer3_2.bn.num_batches_tracked", "module.fam43_2.conv_d1.weight", "module.fam43_2.conv_d1.bias", "module.fam43_2.conv_l.weight", "module.fam43_2.conv_l.bias", "module.fam43_2.conv3.weight", "module.fam43_2.conv3.bias", "module.fam43_2.bn3.weight", "module.fam43_2.bn3.bias", "module.fam43_2.bn3.running_mean", "module.fam43_2.bn3.running_var", "module.fam43_2.bn3.num_batches_tracked", "module.final.0.conv.weight", "module.final.0.conv.bias", "module.final.0.bn.weight", "module.final.0.bn.bias", "module.final.0.bn.running_mean", "module.final.0.bn.running_var", "module.final.0.bn.num_batches_tracked", "module.final.1.conv.weight", "module.final.1.conv.bias", "module.final2.0.conv.weight", "module.final2.0.conv.bias", "module.final2.0.bn.weight", "module.final2.0.bn.bias", "module.final2.0.bn.running_mean", "module.final2.0.bn.running_var", "module.final2.0.bn.num_batches_tracked", "module.final2.1.conv.weight", "module.final2.1.conv.bias", "module.final_2.0.conv.weight", "module.final_2.0.conv.bias", "module.final_2.0.bn.weight", "module.final_2.0.bn.bias", "module.final_2.0.bn.running_mean", "module.final_2.0.bn.running_var", "module.final_2.0.bn.num_batches_tracked", "module.final_2.1.conv.weight", "module.final_2.1.conv.bias", "module.final2_2.0.conv.weight", "module.final2_2.0.conv.bias", "module.final2_2.0.bn.weight", "module.final2_2.0.bn.bias", "module.final2_2.0.bn.running_mean", "module.final2_2.0.bn.running_var", "module.final2_2.0.bn.num_batches_tracked", "module.final2_2.1.conv.weight", "module.final2_2.1.conv.bias". 
请问是什么原因呢，权重文件是提供的连接里边下载的

**Comment by lewisli66** [comment]
你好，请问这个问题解决了没，我也遇到了同样的问题

**Comment by JackLiu-97** [comment]
还没有解决
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/25/2023 10:01 |
| To | ZhengJianwei2/DMINet ***@***.***> |
| Cc | ChenglongLiu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ZhengJianwei2/DMINet] demo.py (Issue #3) |

你好，请问这个问题解决了没，我也遇到了同样的问题

**Comment by zlin9** [comment]
> 还没有解决 ---- Replied Message ---- | From | ***@***.***> | | Date | 07/25/2023 10:01 | | To | ZhengJianwei2/DMINet ***@***.***> | | Cc | ChenglongLiu ***@***.***>, Author ***@***.***> | | Subject | Re: [ZhengJianwei2/DMINet] demo.py (Issue #3) | 你好，请问这个问题解决了没，我也遇到了同样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，请问这个问题你解决了吗，我猜测是不是模型和权重文件不匹配导致的问题。

**Comment by fengyuchao97** [comment]
这个问题应该是双卡训练和单卡测试的问题，兄弟们，把models/evaluator.py 里面的74行代码 self.net_G = nn.DataParallel(self.net_G) 注不注释来控制

**Comment by kinjackman** [comment]
您好，解决这个问题了吗？

**Comment by kinjackman** [comment]
> 这个问题应该是双卡训练和单卡测试的问题，兄弟们，把models/evaluator.py 里面的74行代码 self.net_G = nn.DataParallel(self.net_G) 注不注释来控制
学长，注册掉还是会出现这个问题

**Comment by fengyuchao97** [comment]
你加我微信吧 我也不知道你遇到了啥问题fyc526338

发自我的iPhone


------------------ Original ------------------
From: kinjackman ***@***.***&gt;
Date: Fri,May 31,2024 11:30 AM
To: ZhengJianwei2/DMINet ***@***.***&gt;
Cc: FengYuchao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ZhengJianwei2/DMINet] demo.py (Issue #3)





  
这个问题应该是双卡训练和单卡测试的问题，兄弟们，把models/evaluator.py 里面的74行代码 self.net_G = nn.DataParallel(self.net_G) 注不注释来控制
 学长，注册掉还是会出现这个问题
